apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: test
  name: ptest
  namespace: test
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080 
      path: /metrics
  selector:
    matchLabels:
      app: test