all:
  hosts:
    master-1:
      ansible_host:  192.168.254.10
      ansible_user: arcter
      ansible_become: yes
    worker-1:
      ansible_host:  192.168.254.11
      ansible_user: arcter
      ansible_become: yes
    worker-2:
      ansible_host:  192.168.254.12
      ansible_user: arcter
      ansible_become: yes
    nfs:
      ansible_host:  192.168.254.21
      ansible_user: arcter
      ansible_become: yes
  children:
    k8s:
      children:
        workers:
          hosts:
            worker-1:
            worker-2:
        masters:
          hosts:
            master-1:
    supports:
      hosts:
        nfs: