- name: Prep the nodes
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: nfs-common
        state: present

- name: Prep the nodes
  hosts: k8s
  become: true
  tasks:
   - name: Download install script
     ansible.builtin.get_url:
        url: https://get.rke2.io
        dest: /tmp/rke.sh
        mode: '0551'
   - name: Set memory limits
     ansible.posix.sysctl:
        name: vm.max_map_count
        value: '262144'
        sysctl_file: /etc/sysctl.conf
        reload: true

- name: Install master-1
  hosts: masters
  become: true
  tasks:
    - name: Install script
      ansible.builtin.shell: /tmp/rke.sh
    - name: Start service rke2, if not started
      ansible.builtin.service:
        name: rke2-server.service
        enabled: yes
        state: started
    - name: get node-token
      ansible.builtin.fetch:
        src: /var/lib/rancher/rke2/server/node-token
        dest: tmp/token
        flat: yes

- name: Install workers
  hosts: workers
  vars:
    server: "192.168.254.10"
    token:  "{{lookup('file', 'tmp/token') }}"
  become: true
  tasks:
    - name: Template config file
      ansible.builtin.template:
        src: templates/config.yaml
        dest: /etc/rancher/rke2/
        owner: root
        group: root
        mode: '0644'
    - name: Run install script
      ansible.builtin.shell: /tmp/rke.sh
      environment:
        INSTALL_RKE2_TYPE: agent
    - name: Start service rke2, if not started
      ansible.builtin.service:
        name: rke2-agent.service
        enabled: yes
        state: started

- name: Install NFS
  hosts: nfs
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: nfs-kernel-server
        state: present

    - name: Make directory
      ansible.builtin.file:
        path: /NFS
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'
    - name: Copy config
      ansible.builtin.copy:
        src: files/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
    - name: Restart nfs service
      ansible.builtin.service:
        name: nfs-kernel-server.service
        enabled: yes
        state: restarted